# Generated by Django 2.2.3 on 2019-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='Barcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
