# Generated by Django 2.2.6 on 2019-11-02 22:34

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlypage', '0002_camera_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='Barcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره سریال'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='Enddateofwarranty',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ اتمام گارانتی'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='Startdayofwarranty',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع گارانتی'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
